import pytest
from datetime import date, timedelta, datetime

from . import data_service

def make_iso(d: date) -> str:
    # returns ISO format with time to match repo data
    return datetime.combine(d, datetime.min.time()).isoformat()


def test_get_number_active_members(monkeypatch):
    monkeypatch.setattr(data_service, 'getNumberActiveMembersFromRepo', lambda: [{"status": "active"}, {"status": "active"}, {"status": "active"}])
    assert data_service.getNumberActiveMembers() == 3


def test_get_member_types_data(monkeypatch):
    # 2 Basic, 1 VIP
    sample = [
        {'tier': 'Basic'},
        {'tier': 'VIP'},
        {'tier': 'Basic'},
    ]
    monkeypatch.setattr(data_service, 'getMemberTypesDataFromRepo', lambda: sample)
    tiers, counts = data_service.getMemberTypesData()

    # have to convert back to dictionary because the exact order generated by Counter is not predictable
    result = dict(zip(tiers, counts))
    assert result == {'Basic': 2, 'VIP': 1}


def test_get_class_popularity(monkeypatch):
    sample = [
        {'class_name': 'Yoga', 'total_bookings': 10},
        {'class_name': 'Boxing', 'total_bookings': 30},
        {'class_name': 'Yoga', 'total_bookings': 5},
    ]
    monkeypatch.setattr(data_service, 'getClassNamesFromRepo', lambda: sample)
    names, counts = data_service.getClassPopularityData()

    # most popular (top of list) is Boxing
    assert names[0] == 'Boxing'
    assert counts[0] == 30

    # Yoga is 10 + 5 = 15
    assert 'Yoga' in names and counts[names.index('Yoga')] == 15


def test_get_class_times_popularity(monkeypatch):
    sample = [
        {'time': '10:00:00', 'total_bookings': 5},
        {'time': '10:00:00', 'total_bookings': 10},
        {'time': '11:00:00', 'total_bookings': 3},
    ]
    monkeypatch.setattr(data_service, 'getClassTimesFromRepo', lambda: sample)
    times, counts = data_service.getClassTimesPopularityData()

    # 10:00 is most popular class time of 10 + 5 = 15
    assert times[0] == '10:00'
    assert counts[0] == 15


def test_get_signups_and_cancellations_grouping(monkeypatch):
    today = date.today()

    # signup 60 days ago
    d1 = today - timedelta(days=60)

    # signup 30 days ago
    d2 = today - timedelta(days=30)

    # one cancellation that already ended
    cancel_date = today - timedelta(days=15)

    sample = [
        {'created_at': make_iso(d1), 'current_period_end': None},
        {'created_at': make_iso(d2), 'current_period_end': make_iso(cancel_date)},
    ]

    monkeypatch.setattr(data_service, 'getSignupsAndCancellationsDataFromRepo', lambda: sample)
    signups, cancellations = data_service.getSignupsAndCancellationsData()

    # expected months
    m1 = d1.strftime('%Y-%m')
    m2 = d2.strftime('%Y-%m')
    mc = cancel_date.strftime('%Y-%m')

    signups_dict = dict(signups)
    cancellations_dict = dict(cancellations)

    # both months should appear with at least 1 signup
    assert signups_dict.get(m1, 0) >= 1
    assert signups_dict.get(m2, 0) >= 1
    # cancellation month should have at least 1
    assert cancellations_dict.get(mc, 0) >= 1


def test_get_membership_data_cumulative(monkeypatch):
    today = date.today()

    # signup 2 days ago
    s1 = today - timedelta(days=2)

    # signup yesterday
    s2 = today - timedelta(days=1)

    # cancellation yesterday
    c1 = today - timedelta(days=1)

    sample = [
        {'created_at': make_iso(s1), 'current_period_end': None},
        {'created_at': make_iso(s2), 'current_period_end': make_iso(c1)},
    ]

    monkeypatch.setattr(data_service, 'getMembershipDataFromRepo', lambda: sample)
    memberships = data_service.getMembershipData()

    # memberships is a list of [date_str, cumulative_count]
    # get number of memberships on latest day
    last = memberships[-1][1]
    # 2 signups minus 1 cancellation = 1
    assert last == 1
